import Head from 'next/head'
import Image from 'next/image'
import MUIDataTable from "mui-datatables";
import { useEffect, useState } from 'react'

export default function Home() {

  const [columns, setColumns] = useState([])
  const [data, setData] = useState([])

  useEffect(() => {
    setColumns(
      [
        {
          name: "id",
          label: "ID",
          options: {
            display: false,
          }
        },
        {
          name: "name",
          label: "Name",
          options: {
            filter: true,
            sort: true,
          }
        },
        {
          name: "company",
          label: "Company",
          options: {
            filter: true,
            sort: false,
          }
        },
        {
          name: "city",
          label: "City",
          options: {
            filter: true,
            sort: false,
          }
        },
        {
          name: "state",
          label: "State",
          options: {
            filter: true,
            sort: false,
          }
        },
      ]
    )

    setData(
      [
        { id: 1, name: "Joe James", company: "Test Corp", city: "Yonkers", state: "NY" },
        { id: 2, name: "John Walsh", company: "Test Corp", city: "Hartford", state: "CT" },
        { id: 3, name: "Bob Herm", company: "Test Corp", city: "Tampa", state: "FL" },
        { id: 4, name: "James Houston", company: "Test Corp", city: "Dallas", state: "TX" },
      ]
    )

  }, [])


  const options = {
    filterType: 'checkbox',
    onRowSelectionChange: (c, s) => {
      let a = s.map((r) => r.dataIndex)
      a.map((i) => {
        let datas = data.find((r, index) => index == i)
        console.log(datas)
      })
    },
    onRowsDelete: (a, b) => {
      console.log(a)
      console.log(b)
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MUIDataTable
        title={"Employee List"}
        data={data}
        columns={columns}
        options={options}
      />
    </div>
  )
}
